apiVersion: v1
kind: Namespace
metadata:
  name: app-prod
  labels:
    pod-security.kubernetes.io/enforce: restricted # manifests must meet the restricted Pod Security Standard
    pod-security.kubernetes.io/enforce-version: latest
