apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-dev
resources:
  - namespace.yaml
  - ../../base
images:
  - name: ghcr.io/brianmahlatini/k8s-gitops-app
    newTag: sha-bootstrap # CI rewrites this to sha-<commit> on every main build
patches:
  - target: { kind: HorizontalPodAutoscaler, name: app }
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
  - target: { kind: Deployment, name: app }
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - { name: APP_ENV, value: dev }
          - { name: LOG_LEVEL, value: debug }
