apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-gitops-app
  namespace: argocd
spec:
  description: Demo app delivered by GitOps
  sourceRepos:
    - https://github.com/brianmahlatini/k8s-gitops-app.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: app-dev
    - server: https://kubernetes.default.svc
      namespace: app-prod
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
